feat(create): add performCreate[2] method.
alchemyplatform/modular-account pull request #168
Opened 2024-07-30 19:10 UTC by andysim3d

## Motivation

## Solution

2024-08-01 18:41 UTC, jaypaik requested changes
Thanks for getting this in! Some nits.

2024-08-01 18:41 UTC, jaypaik commented on src/account/UpgradeableModularAccount.sol
> +    error CreateFailed();
Nit: sort errors

2024-08-01 18:41 UTC, jaypaik commented on src/account/UpgradeableModularAccount.sol
> +    /// @param initCode The initCode to deploy.
Nit: Probably makes sense to copy over the entire natspec block from Light Account: https://github.com/alchemyplatform/light-account/blob/ebe761ac15a2be210f94015f9f706b86fcf7e099/src/common/BaseLightAccount.sol#L79-L89

2024-08-01 18:41 UTC, jaypaik commented on src/account/UpgradeableModularAccount.sol
> +    /// @param salt The salt to use for the create2 operation.
Same.

2024-08-01 18:41 UTC, jaypaik commented on test/account/UpgradeableModularAccount.t.sol
> +        address expectedAddr = computeCreateAddress(account, vm.getNonce(account));
Nit: Perhaps `vm.computeCreateAddress` to be more explicit?

2024-08-01 18:41 UTC, jaypaik commented on test/account/UpgradeableModularAccount.t.sol
> +        // multi-depoly with same salt got reverted
```suggestion
        // multi-deploy with same salt got reverted
```

2024-08-01 18:54 UTC, adamegyed reviewed
Flagging that we're missing access control on these methods. In the past we could have used a modifier like `wrapNativeFunction`, but we've removed that in this repo for code size optimization. We should wrap the two functions with the following:
```solidity
(FunctionReference[][] memory postExecHooks, bytes[] memory postHookArgs) = _preNativeFunction();
// function body
_postNativeFunction(postExecHooks, postHookArgs);
```

2024-08-14 15:40 UTC, andysim3d commented on src/account/UpgradeableModularAccount.sol
> +    error CreateFailed();
Done

2024-08-14 15:40 UTC, andysim3d commented on src/account/UpgradeableModularAccount.sol
> +    /// @param initCode The initCode to deploy.
Done

2024-08-14 15:40 UTC, andysim3d commented on src/account/UpgradeableModularAccount.sol
> +    /// @param salt The salt to use for the create2 operation.
Done

2024-08-14 15:45 UTC, andysim3d commented on test/account/UpgradeableModularAccount.t.sol
> +        address expectedAddr = computeCreateAddress(account, vm.getNonce(account));
I use computeCreateAddress here because the version of "forge-std/Test.sol" is not merge computeCreateAddress in VM package.

it was merged in 1.7.3: https://github.com/foundry-rs/forge-std/releases/tag/v1.7.3

2024-08-14 15:45 UTC, andysim3d commented on test/account/UpgradeableModularAccount.t.sol
> +        // multi-depoly with same salt got reverted
Done

2024-08-14 16:13 UTC, andysim3d commented
> Flagging that we're missing access control on these methods. In the past we could have used a modifier like `wrapNativeFunction`, but we've removed that in this repo for code size optimization. We should wrap the two functions with the following:
> 
> ```solidity
> (FunctionReference[][] memory postExecHooks, bytes[] memory postHookArgs) = _preNativeFunction();
> // function body
> _postNativeFunction(postExecHooks, postHookArgs);
> ```

I'll address in following pr. right now I am not sure the correct modifier to use here.

2024-09-26 19:18 UTC, Zer0dot commented
Superseded for MAv2 by #192, closing this as it's targeting MAv1. Great work though Andy!

2024-09-26 19:18 UTC, closed without merging